# Generated by Django 3.0.7 on 2020-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200712_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='days',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
